lerobot-train \
    --dataset.repo_id=zhiyuan/pick_place \
    --dataset.root=/home/zhiyuan/.cache/huggingface/lerobot/zhiyuan/pick_place \
    --policy.type=act \
    --output_dir=outputs/train_act_test \
    --job_name=act_test \
    --policy.device=cuda \
    --wandb.enable=true \
    --wandb.project=Lerobot_Project \
    --policy.push_to_hub=false \
    --steps=1000 \
    --batch_size=8