lerobot-train \
    --dataset.repo_id=<username>/record-test \
    --dataset.root=${HOME}/.cache/huggingface/lerobot/<username>/record-test \
    --policy.type=act \
    --output_dir=outputs/train_act_test \
    --job_name=act_test \
    --policy.device=cuda \
    --wandb.enable=true \
    --wandb.project=Lerobot_Project \
    --policy.push_to_hub=false \
    --steps=200000 \
    --batch_size=8