lerobot-train \
  --dataset.repo_id=ZhiyuanZhangZhiyuan/lerobot_hanging \
  --dataset.revision=v0.4.0 \
  --dataset.root=/scratch/gilbreth/zhan5570/Project/lerobot/data/lerobot_hanging \
  --dataset.streaming=false \
  --policy.type=act \
  --policy.device=cuda \
  --output_dir=training_outputs/hanging_act \
  --job_name=hanging_act \
  --wandb.enable=true \
  --wandb.project=lerobot \
  --policy.push_to_hub=false \
  --steps=200000 \
  --batch_size=8
